/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CallTTSservice_H
#define CallTTSservice_H

#include <thrift/TDispatchProcessor.h>
#include "tts_types.h"



class CallTTSserviceIf {
 public:
  virtual ~CallTTSserviceIf() {}
  virtual void callTTS(Response& _return, const Request& request) = 0;
};

class CallTTSserviceIfFactory {
 public:
  typedef CallTTSserviceIf Handler;

  virtual ~CallTTSserviceIfFactory() {}

  virtual CallTTSserviceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(CallTTSserviceIf* /* handler */) = 0;
};

class CallTTSserviceIfSingletonFactory : virtual public CallTTSserviceIfFactory {
 public:
  CallTTSserviceIfSingletonFactory(const boost::shared_ptr<CallTTSserviceIf>& iface) : iface_(iface) {}
  virtual ~CallTTSserviceIfSingletonFactory() {}

  virtual CallTTSserviceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(CallTTSserviceIf* /* handler */) {}

 protected:
  boost::shared_ptr<CallTTSserviceIf> iface_;
};

class CallTTSserviceNull : virtual public CallTTSserviceIf {
 public:
  virtual ~CallTTSserviceNull() {}
  void callTTS(Response& /* _return */, const Request& /* request */) {
    return;
  }
};

typedef struct _CallTTSservice_callTTS_args__isset {
  _CallTTSservice_callTTS_args__isset() : request(false) {}
  bool request;
} _CallTTSservice_callTTS_args__isset;

class CallTTSservice_callTTS_args {
 public:

  CallTTSservice_callTTS_args() {
  }

  virtual ~CallTTSservice_callTTS_args() throw() {}

  Request request;

  _CallTTSservice_callTTS_args__isset __isset;

  void __set_request(const Request& val) {
    request = val;
  }

  bool operator == (const CallTTSservice_callTTS_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const CallTTSservice_callTTS_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CallTTSservice_callTTS_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CallTTSservice_callTTS_pargs {
 public:


  virtual ~CallTTSservice_callTTS_pargs() throw() {}

  const Request* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CallTTSservice_callTTS_result__isset {
  _CallTTSservice_callTTS_result__isset() : success(false) {}
  bool success;
} _CallTTSservice_callTTS_result__isset;

class CallTTSservice_callTTS_result {
 public:

  CallTTSservice_callTTS_result() {
  }

  virtual ~CallTTSservice_callTTS_result() throw() {}

  Response success;

  _CallTTSservice_callTTS_result__isset __isset;

  void __set_success(const Response& val) {
    success = val;
  }

  bool operator == (const CallTTSservice_callTTS_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const CallTTSservice_callTTS_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CallTTSservice_callTTS_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CallTTSservice_callTTS_presult__isset {
  _CallTTSservice_callTTS_presult__isset() : success(false) {}
  bool success;
} _CallTTSservice_callTTS_presult__isset;

class CallTTSservice_callTTS_presult {
 public:


  virtual ~CallTTSservice_callTTS_presult() throw() {}

  Response* success;

  _CallTTSservice_callTTS_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class CallTTSserviceClient : virtual public CallTTSserviceIf {
 public:
  CallTTSserviceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  CallTTSserviceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void callTTS(Response& _return, const Request& request);
  void send_callTTS(const Request& request);
  void recv_callTTS(Response& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class CallTTSserviceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<CallTTSserviceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (CallTTSserviceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_callTTS(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  CallTTSserviceProcessor(boost::shared_ptr<CallTTSserviceIf> iface) :
    iface_(iface) {
    processMap_["callTTS"] = &CallTTSserviceProcessor::process_callTTS;
  }

  virtual ~CallTTSserviceProcessor() {}
};

class CallTTSserviceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  CallTTSserviceProcessorFactory(const ::boost::shared_ptr< CallTTSserviceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< CallTTSserviceIfFactory > handlerFactory_;
};

class CallTTSserviceMultiface : virtual public CallTTSserviceIf {
 public:
  CallTTSserviceMultiface(std::vector<boost::shared_ptr<CallTTSserviceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~CallTTSserviceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<CallTTSserviceIf> > ifaces_;
  CallTTSserviceMultiface() {}
  void add(boost::shared_ptr<CallTTSserviceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void callTTS(Response& _return, const Request& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->callTTS(_return, request);
    }
    ifaces_[i]->callTTS(_return, request);
    return;
  }

};



#endif
