/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tts_CONSTANTS_H
#define tts_CONSTANTS_H

#include "tts_types.h"



class ttsConstants {
 public:
  ttsConstants();

};

extern const ttsConstants g_tts_constants;



#endif
