/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "tts_constants.h"



const ttsConstants g_tts_constants;

ttsConstants::ttsConstants() {
}



